//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraSua
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuaChon
    {
        public int MaLuaChon { get; set; }
        public int MaSanPham { get; set; }
        public int MaTopping { get; set; }
    
        public virtual MaLuaChon MaLuaChon1 { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
