//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraSua
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyTraSuaEntities : DbContext
    {
        public QuanLyTraSuaEntities()
            : base("name=QuanLyTraSuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDonChiTiet> HoaDonChiTiets { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LuaChon> LuaChons { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
    
        [DbFunction("QuanLyTraSuaEntities", "ThongKeHoaDonTheoCacThang")]
        public virtual IQueryable<ThongKeHoaDonTheoCacThang_Result> ThongKeHoaDonTheoCacThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeHoaDonTheoCacThang_Result>("[QuanLyTraSuaEntities].[ThongKeHoaDonTheoCacThang]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "ThongKeSanPhamTheoCacThang")]
        public virtual IQueryable<ThongKeSanPhamTheoCacThang_Result> ThongKeSanPhamTheoCacThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeSanPhamTheoCacThang_Result>("[QuanLyTraSuaEntities].[ThongKeSanPhamTheoCacThang]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "ThongKeTienBanDuocTheoThang")]
        public virtual IQueryable<ThongKeTienBanDuocTheoThang_Result> ThongKeTienBanDuocTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeTienBanDuocTheoThang_Result>("[QuanLyTraSuaEntities].[ThongKeTienBanDuocTheoThang]()");
        }
    }
}
