//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTraSua
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyTraSuaEntities : DbContext
    {
        public QuanLyTraSuaEntities()
            : base("name=QuanLyTraSuaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDonChiTiet> HoaDonChiTiets { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LuaChon> LuaChons { get; set; }
        public virtual DbSet<MaLuaChon> MaLuaChons { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllGiamGia")]
        public virtual IQueryable<GetAllGiamGia_Result> GetAllGiamGia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllGiamGia_Result>("[QuanLyTraSuaEntities].[GetAllGiamGia]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllGiamGiaByTenKhuyenMai")]
        public virtual IQueryable<GetAllGiamGiaByTenKhuyenMai_Result> GetAllGiamGiaByTenKhuyenMai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllGiamGiaByTenKhuyenMai_Result>("[QuanLyTraSuaEntities].[GetAllGiamGiaByTenKhuyenMai]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllHoaDonChiTiet")]
        public virtual IQueryable<GetAllHoaDonChiTiet_Result> GetAllHoaDonChiTiet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllHoaDonChiTiet_Result>("[QuanLyTraSuaEntities].[GetAllHoaDonChiTiet]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllHoaDonChiTietByMaHoaDon")]
        public virtual IQueryable<GetAllHoaDonChiTietByMaHoaDon_Result> GetAllHoaDonChiTietByMaHoaDon(Nullable<int> maHoaDon)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("maHoaDon", maHoaDon) :
                new ObjectParameter("maHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllHoaDonChiTietByMaHoaDon_Result>("[QuanLyTraSuaEntities].[GetAllHoaDonChiTietByMaHoaDon](@maHoaDon)", maHoaDonParameter);
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllHoaDonChiTietByMaLuaChon")]
        public virtual IQueryable<GetAllHoaDonChiTietByMaLuaChon_Result> GetAllHoaDonChiTietByMaLuaChon(Nullable<int> maLuaChon)
        {
            var maLuaChonParameter = maLuaChon.HasValue ?
                new ObjectParameter("maLuaChon", maLuaChon) :
                new ObjectParameter("maLuaChon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllHoaDonChiTietByMaLuaChon_Result>("[QuanLyTraSuaEntities].[GetAllHoaDonChiTietByMaLuaChon](@maLuaChon)", maLuaChonParameter);
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetAllPhanQuyen")]
        public virtual IQueryable<GetAllPhanQuyen_Result> GetAllPhanQuyen()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllPhanQuyen_Result>("[QuanLyTraSuaEntities].[GetAllPhanQuyen]()");
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetGiamGiaByMaHoaDon")]
        public virtual IQueryable<GetGiamGiaByMaHoaDon_Result> GetGiamGiaByMaHoaDon(Nullable<int> maHoaDon)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("maHoaDon", maHoaDon) :
                new ObjectParameter("maHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetGiamGiaByMaHoaDon_Result>("[QuanLyTraSuaEntities].[GetGiamGiaByMaHoaDon](@maHoaDon)", maHoaDonParameter);
        }
    
        [DbFunction("QuanLyTraSuaEntities", "GetPhanQuyenByMaTaiKhoan")]
        public virtual IQueryable<GetPhanQuyenByMaTaiKhoan_Result> GetPhanQuyenByMaTaiKhoan(Nullable<int> maTaiKhoan)
        {
            var maTaiKhoanParameter = maTaiKhoan.HasValue ?
                new ObjectParameter("maTaiKhoan", maTaiKhoan) :
                new ObjectParameter("maTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPhanQuyenByMaTaiKhoan_Result>("[QuanLyTraSuaEntities].[GetPhanQuyenByMaTaiKhoan](@maTaiKhoan)", maTaiKhoanParameter);
        }
    
        [DbFunction("QuanLyTraSuaEntities", "ThongKeHoaDonTheoCacThang")]
        public virtual IQueryable<ThongKeHoaDonTheoCacThang_Result> ThongKeHoaDonTheoCacThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeHoaDonTheoCacThang_Result>("[QuanLyTraSuaEntities].[ThongKeHoaDonTheoCacThang]()");
        }
    
        public virtual int DeletePhanQuyen(Nullable<int> maTaiKhoan, Nullable<int> maQuyen)
        {
            var maTaiKhoanParameter = maTaiKhoan.HasValue ?
                new ObjectParameter("maTaiKhoan", maTaiKhoan) :
                new ObjectParameter("maTaiKhoan", typeof(int));
    
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("maQuyen", maQuyen) :
                new ObjectParameter("maQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePhanQuyen", maTaiKhoanParameter, maQuyenParameter);
        }
    
        public virtual int DeletePhanQuyenByMaQuyen(Nullable<int> maQuyen)
        {
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("maQuyen", maQuyen) :
                new ObjectParameter("maQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePhanQuyenByMaQuyen", maQuyenParameter);
        }
    
        public virtual int DeletePhanQuyenByMaTaiKhoan(Nullable<int> maTaiKhoan)
        {
            var maTaiKhoanParameter = maTaiKhoan.HasValue ?
                new ObjectParameter("maTaiKhoan", maTaiKhoan) :
                new ObjectParameter("maTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletePhanQuyenByMaTaiKhoan", maTaiKhoanParameter);
        }
    
        public virtual int PostGiamGia(Nullable<int> maKhuyenMai, Nullable<int> maHoaDon)
        {
            var maKhuyenMaiParameter = maKhuyenMai.HasValue ?
                new ObjectParameter("maKhuyenMai", maKhuyenMai) :
                new ObjectParameter("maKhuyenMai", typeof(int));
    
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("maHoaDon", maHoaDon) :
                new ObjectParameter("maHoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PostGiamGia", maKhuyenMaiParameter, maHoaDonParameter);
        }
    
        public virtual int PostHoaDonChiTiet(Nullable<int> maHoaDon, Nullable<int> maLuaChon)
        {
            var maHoaDonParameter = maHoaDon.HasValue ?
                new ObjectParameter("maHoaDon", maHoaDon) :
                new ObjectParameter("maHoaDon", typeof(int));
    
            var maLuaChonParameter = maLuaChon.HasValue ?
                new ObjectParameter("maLuaChon", maLuaChon) :
                new ObjectParameter("maLuaChon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PostHoaDonChiTiet", maHoaDonParameter, maLuaChonParameter);
        }
    
        public virtual int PostPhanQuyen(Nullable<int> maTaiKhoan, Nullable<int> maQuyen)
        {
            var maTaiKhoanParameter = maTaiKhoan.HasValue ?
                new ObjectParameter("maTaiKhoan", maTaiKhoan) :
                new ObjectParameter("maTaiKhoan", typeof(int));
    
            var maQuyenParameter = maQuyen.HasValue ?
                new ObjectParameter("maQuyen", maQuyen) :
                new ObjectParameter("maQuyen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PostPhanQuyen", maTaiKhoanParameter, maQuyenParameter);
        }
    
        [DbFunction("QuanLyTraSuaEntities", "ThongKeHoaDonTheoCacThangByMaNhanVien")]
        public virtual IQueryable<ThongKeHoaDonTheoCacThangByMaNhanVien_Result> ThongKeHoaDonTheoCacThangByMaNhanVien(Nullable<int> maNhanVien)
        {
            var maNhanVienParameter = maNhanVien.HasValue ?
                new ObjectParameter("maNhanVien", maNhanVien) :
                new ObjectParameter("maNhanVien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeHoaDonTheoCacThangByMaNhanVien_Result>("[QuanLyTraSuaEntities].[ThongKeHoaDonTheoCacThangByMaNhanVien](@maNhanVien)", maNhanVienParameter);
        }
    }
}
